---
  # Message of the Day on the machine.
  - name: change MOTD
    template: src=motd.j2 dest=/etc/motd owner=root mode=0644
    tags: motd

  ##
  # Adding common users to the system.
  #
  - name: add common users
    user: name="{{ item }}" state=present groups=admin, shell='/bin/bash'
    tags: common
    with_items:
      - tur057

  - name: add common user public keys
    authorized_key: user={{ item.name }} key="{{ lookup('file', item.keyfile) }}" state=present
    tags: common
    with_items:
      - { name: 'tur057', keyfile: 'tur057_rsa.pub' }

  - name: Modifiy admins so they need no sudo password
    tags: common
    lineinfile: dest=/etc/sudoers state=present regexp='^%admin ALL\=' line='%admin ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

  - name: Add emacs for everyone.
    tags: common
    apt: pkg='emacs23-nox' state=present

  - name: Add nano for everyone.
    tags: common
    apt: pkg='nano' state=present
